"""Target: write the harness as ``AGENTS.md`` for Codex CLI / generic agents."""

from __future__ import annotations

from codagent.targets._file_target import _FileApplyTarget


class apply_to_agents_md(_FileApplyTarget):
    relative_path = "AGENTS.md"
    file_header = "# AGENTS.md\n\n_Generated by codagent._"
    name = "agents_md"
