"""Target: write the harness as ``.github/copilot-instructions.md``.

GitHub Copilot Chat in VS Code, JetBrains, and Visual Studio reads
this file automatically.
"""

from __future__ import annotations

from codagent.harness.targets._file_target import _FileApplyTarget


class apply_to_copilot(_FileApplyTarget):
    relative_path = ".github/copilot-instructions.md"
    file_header = "# Copilot Instructions\n\n_Generated by codagent._"
    name = "copilot"
